app/views/main.py
from flask import Blueprint,render_template,redirect,url_for,flash,request
from app.models import Posts
from app.forms import PostForm
from app.extensions import db
from flask_login import current_user
main = Blueprint('main', __name__)


@main.route('/', methods=['POST', 'GET'])
def index():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            u = current_user._get_current_object()
            p = Posts(content=form.content.data,user=u)
            db.session.add(p)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('请先登录')
            return redirect(url_for('users.login'))
    # posts = Posts.query.filter_by(rid=0).all()
    page = request.args.get('p',1,type=int)
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).paginate(page,per_page=5,error_out=False)
    posts = pagination.items
    return render_template('main/index.html',form=form,posts=posts,pagination=pagination)

app/views/posts.py
from flask import Blueprint,jsonify
from flask_login import current_user

posts = Blueprint('posts',__name__)

@posts.route('/collect/<int:pid>')
def collect(pid):
    if current_user.is_favorite(pid):
        current_user.def_favorite(pid)
    else:
        current_user.add_favorite(pid)
    return jsonify({'resulet':'OK'})

app/templates/main/index.html
{% extends 'common/base.html' %}
{% from 'common/macro.html'import pagination_show %}
{% block title %}首页{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
    {% for p in posts %}
            <div class="media">
        <div class="media-left">
            <a href="#">
                <img class="media-object" src="{{ url_for('static',filename='uploads/'+p.user.icon) }}" alt="头像" style="width: 64px;height: 64px">
            </a>
        </div>
        <div class="media-body">
            <div style="float:right">{{ moment(p.timestamp).fromNow() }}</div>
            <h4 class="media-heading">{{ p.user.username }}</h4>
            {{ p.content }}
            {% if current_user.is_authenticated %}
                <div class="collect"url = "{{ url_for('posts.collect',pid =p.id)}} "style="cursor: pointer;">
                   {% if current_user.is_favorite(p.id) %}
                       取消收藏
                       {% else %}
                       收藏
                   {% endif %}

                </div>

            {% endif %}
        </div>
    </div>
    {% endfor %}
{#    {{ super() }}#}
    {{ pagination_show(pagination,'main.index') }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        $(function () {
            $('.collect').click(function () {
                _this = this
                $.get($(this).attr('url'), function(){
                        if ($(_this).text()=='收藏'){
                              $(_this).text('取消收藏')
                        } else {
                              $(_this).text('收藏')
                        }
                });
            })
        })

    </script>
{% endblock %}