app/views/users.py
from flask import Blueprint,request,render_template,flash,redirect,url_for,current_app
from app.forms import RegisterForm,LoginForm,UploadForm,ChangePasswordForm,ChangeEmailForm
from app.extensions import db,photos
from app.models import Users
from app.email import send_mail
from flask_login import login_user,logout_user,login_required,current_user
import os
from PIL import Image

users = Blueprint('users', __name__)


@users.route('/register/', methods=['POST', 'GET'])
def register():
    form =RegisterForm(request.form)
    if form.validate():
        u = Users(username=form.username.data,
                  password=form.password.data,
                  email=form.email.data)
        db.session.add(u)
        db.session.commit()
        token = u.generate_active_token()
        send_mail(u.email,'账户激活','email/activate',username=u.username,token=token)
        flash('该用户已经注册，请点击邮件中的链接完成激活')
        return redirect(url_for('main.index'))
    return render_template('users/register.html',form=form)


@users.route('/activate/<token>/')
def acticvate(token):
    if Users.check_activate_token(token):
        flash('账户已经激活')
        return redirect(url_for('users.login'))
    else:
        flash('账户激活失败')
        return redirect(url_for('main.index'))

@users.route('/login/',methods=['POST','GET'])
def login():
    form = LoginForm(request.form)
    if form.validate():
        u = Users.query.filter_by(username=form.username.data).first()
        if not u:
            flash('该用户不存在')
        elif not u.confirmed:
            flash('该账户没有激活，请先激活')
        elif u.verify_password(form.password.data):
            login_user(u,remember=form.remember.data)
            flash('登陆成功')
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('登陆失败')
    return render_template('users/login.html',form=form)


@users.route('/logout/',methods=['POST','GET'])
def logout():
    logout_user()
    flash('退出登录')
    return redirect(url_for('main.index'))

@users.route('/profile/',methods=['POST','GET'])
@login_required
def profile():
    return render_template('users/profile.html')


@users.route('/change_icon/',methods=['POST','GET'])
@login_required
def change_icon():
    form = UploadForm()
    if form.validate():
        suffix = os.path.splitext(form.icon.data.filename)[1]
        filename = random_string()+suffix
        photos.save(form.icon.data,name=filename)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],filename)
        img = Image.open(pathname)
        img.thumbnail((128,128))
        img.save(pathname)
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))
        current_user.icon = filename
        db.session.add(current_user)
        db.session.commit()
        flash('图片已经保存')
    img_url = photos.url(current_user.icon)
    return render_template('users/change_icon.html',form=form,img_url=img_url)

@users.route('/change_password/',methods=['POST','GET'])
@login_required
def change_password():
    form = ChangePasswordForm()
    newpassword = form.newpassword.data
    if form.validate():
        if current_user.verify_password(password=form.oldpassword.data):
            current_user.password = newpassword
            db.session.add(current_user)
            db.session.commit()
            flash('密码修改成功')
            return redirect(url_for('main.index'))
        else:
            flash('修改失败')
    return render_template('users/change_password.html',form=form)

@users.route('/change_email/',methods=['POST','GET'])
@login_required
def change_email():
    form = ChangeEmailForm()
    if form.validate():
        if form.oldemail.data == current_user.email:
            current_user.email = form.newemail.data
            current_user.confirmed = 0
            db.session.add(current_user)
            db.session.commit()
            token = current_user.generate_active_token()
            send_mail(current_user.email, '账户激活', 'email/activate', username=current_user.username, token=token)
            flash('邮箱已经修改，请点击邮件中的链接完成激活')
            return redirect(url_for('main.index'))
        else:
            flash('修改失败')
    return render_template('users/change_email.html',form=form)

def random_string(length=32):
    import random
    base_str = 'qwertyuiopasdfghjklzxcvbnm01234567890'
    return ''.join(random.choice(base_str)for i in range(length))

app/templates/common/base.html
{% extends  'bootstrap/base.html'%}

{% import'bootstrap/wtf.html'as wtf %}

{% block title %}{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">大圣博客</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
            <li><a href="{{ url_for("users.logout") }}">退出登录</a></li>
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ url_for('users.profile') }}">个人中心</a></li>
            <li><a href="{{ url_for('users.change_password') }}">修改密码</a></li>
            <li><a href="{{ url_for('users.change_email') }}">修改邮箱</a></li>
            <li><a href="{{ url_for('users.change_icon') }}">修改头像</a></li>
          </ul>
        </li>
        {% else %}
            <li><a href="{{ url_for('users.register') }}">注册</a></li>
            <li><a href="{{ url_for('users.login') }}">登录</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <strong>Warning!</strong> {{ message }}
            </div>

        {% endfor %}

    {% block page_content %}

    {% endblock %}

    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

app/templates/common/macro.html
{% macro pagination_show(pagination,endpoint) %}
   <nav aria-label="Page navigation">
  <ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
      <a href="{% if pagination.has_prev %}{{ url_for(endpoint,p=pagination.prev_num) }}{% else %}#{% endif %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for p in pagination.iter_pages()%}
        {% if p %}
            <li {% if pagination.page == p%}class="active" {% endif %}><a href="{% if pagination.page == p%}#{% else %}{{ url_for(endpoint,p=p) }}{% endif %}">{{ p }}</a></li>
            {% else %}
            <li><a href="#">&hellip;</a></li>
        {% endif %}

    {% endfor %}
     <li {% if not pagination.has_next %} class="disabled" {% endif %}>
      <a href="{% if pagination.has_next %}{{ url_for(endpoint,p=pagination.next_num) }}{% else %}#{% endif %}" aria-label="Previous">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
{% endmacro %}